# Generated by Django 3.2.15 on 2022-09-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
    ]
