# Generated by Django 3.2.15 on 2022-09-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('client_username', models.CharField(default='Create Username', max_length=40)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.IntegerField(blank=True, default=123456789, null=True)),
                ('client_city', models.CharField(blank=True, max_length=140, null=True)),
                ('client_state', models.CharField(blank=True, max_length=10, null=True)),
                ('client_zip', models.CharField(default='123 45', max_length=10)),
                ('client_country', models.CharField(blank=True, max_length=140, null=True)),
                ('contact_ok', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Logins',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BookViewingTime',
        ),
    ]
