# Generated by Django 3.2.15 on 2022-09-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='seats_available',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='slot',
            name='friendly_name',
            field=models.CharField(blank=True, default='15 Min Appointment Slot', max_length=254, null=True),
        ),
    ]
