# Generated by Django 3.2.15 on 2022-09-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0002_auto_20220916_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
