# Generated by Django 3.2.15 on 2022-09-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0002_auto_20220917_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Schedule Viewing Timeslots to Properties'},
        ),
    ]
