# Generated by Django 3.2.15 on 2022-09-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0002_auto_20220921_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginform',
            options={'verbose_name_plural': 'Login'},
        ),
    ]
