# Generated by Django 3.2.15 on 2022-10-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0002_alter_booking_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
