# Generated by Django 3.2.15 on 2022-09-16 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0003_remove_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slot',
            name='friendly_name',
            field=models.CharField(blank=True, default='15 min', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
