# Generated by Django 3.2.15 on 2022-09-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0003_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Schedule Timeslots'},
        ),
    ]
