# Generated by Django 3.2.15 on 2022-09-16 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0004_auto_20220916_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
