# Generated by Django 3.2.15 on 2022-09-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0004_auto_20220915_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='date_booked',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='finish_day',
            new_name='day_finish',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='start_day',
            new_name='day_start',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='finish_lunch',
            new_name='lunch_finish',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='start_lunch',
            new_name='lunch_start',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
