# Generated by Django 3.2.15 on 2022-09-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0005_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Bookings'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='timeslot',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(blank=True, default='15min Viewing', max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
    ]
