# Generated by Django 3.2.15 on 2022-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0005_auto_20220916_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(blank=True, default='ReaBook 15 Minute Property Viewing', max_length=254, null=True),
        ),
    ]
