# Generated by Django 3.2.15 on 2022-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0006_alter_booking_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='viewing_active',
            field=models.BooleanField(default=True),
        ),
    ]
