# Generated by Django 3.2.15 on 2022-09-15 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0006_auto_20220915_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_name',
            field=models.CharField(blank=True, default='ReaBook 15 Minute Property Viewing Appointment', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='Create Username', max_length=254, unique=True),
        ),
    ]
