# Generated by Django 3.2.15 on 2022-09-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0007_booking_viewing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
