# Generated by Django 3.2.15 on 2022-09-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0008_auto_20220915_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(blank=True, default='ReaBook 15 Minute Property Viewing Appointment', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_name',
            field=models.TimeField(default='00:15'),
        ),
    ]
