# Generated by Django 3.2.15 on 2022-09-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0008_booking_friendly_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Bookings Available'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='friendly_name',
        ),
    ]
