# Generated by Django 3.2.15 on 2022-09-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0009_alter_booking_viewing_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
