# Generated by Django 3.2.15 on 2022-09-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0009_auto_20220916_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Assign Slots to Properties'},
        ),
    ]
