# Generated by Django 3.2.15 on 2022-09-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0010_alter_booking_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_username',
            field=models.CharField(default='Create Username', max_length=40),
        ),
    ]
