# Generated by Django 3.2.15 on 2022-09-15 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0011_alter_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.DurationField(default=datetime.time),
        ),
    ]
