# Generated by Django 3.2.15 on 2022-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0011_booking_client_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_username',
            field=models.CharField(blank=True, default='Create Username', max_length=40, null=True),
        ),
    ]
