# Generated by Django 3.2.15 on 2022-09-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0012_alter_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='time_of_viewing',
        ),
    ]
