# Generated by Django 3.2.15 on 2022-09-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0013_alter_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.ForeignKey(blank=True, default='00:15', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bookings.slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.DurationField(),
        ),
    ]
