# Generated by Django 3.2.15 on 2022-09-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0002_alter_property_realtor'),
        ('app_bookings', '0013_rename_time_booking_time_of_viewing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bookings.client'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_properties.property'),
        ),
    ]
