# Generated by Django 3.2.15 on 2022-09-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0014_auto_20220920_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.IntegerField(blank=True, default=123456789, null=True),
        ),
    ]
