# Generated by Django 3.2.15 on 2022-09-15 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0014_auto_20220915_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
