# Generated by Django 3.2.15 on 2022-09-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0015_auto_20220915_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.TimeField(default='00:15'),
        ),
    ]
