# Generated by Django 3.2.15 on 2022-09-15 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0015_auto_20220915_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bookings.slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.DurationField(default=django.utils.timezone.now),
        ),
    ]
