# Generated by Django 3.2.15 on 2022-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0015_alter_client_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default=1, editable=False, max_length=8),
            preserve_default=False,
        ),
    ]
