# Generated by Django 3.2.15 on 2022-09-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0016_booking_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_state',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
