# Generated by Django 3.2.15 on 2022-09-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0016_auto_20220915_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.DurationField(default='00:15'),
        ),
    ]
