# Generated by Django 3.2.15 on 2022-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0017_alter_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='day_finish',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='day_start',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='lunch_finish',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='lunch_start',
            field=models.TimeField(default='13:00'),
        ),
    ]
