# Generated by Django 3.2.15 on 2022-09-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0019_alter_slot_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name_plural': 'Appointment Slots'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='duration',
            new_name='appointment_slot',
        ),
    ]
