# Generated by Django 3.2.15 on 2022-09-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0020_auto_20220915_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='location',
            new_name='property_id',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='location',
            new_name='property_id',
        ),
    ]
