# Generated by Django 3.2.15 on 2022-09-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0021_auto_20220915_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='prop_id_string',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='property_id'),
        ),
    ]
