# Generated by Django 3.2.15 on 2022-09-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0022_slot_prop_id_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='prop_id_string',
        ),
    ]
