# Generated by Django 3.2.15 on 2022-09-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0023_remove_slot_prop_id_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='slot_name',
            new_name='name',
        ),
    ]
