# Generated by Django 3.2.15 on 2022-09-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0024_rename_slot_name_slot_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='property_id',
            new_name='property_key',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='property_id',
            new_name='property_key',
        ),
    ]
