# Generated by Django 3.2.15 on 2022-09-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0025_auto_20220915_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='property_key',
            new_name='property_tile_no',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='property_key',
            new_name='property_tile_no',
        ),
    ]
