# Generated by Django 3.2.15 on 2022-09-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0026_auto_20220915_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='property_tile_no',
            new_name='property_title_no',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='property_tile_no',
            new_name='property_title_no',
        ),
    ]
