# Generated by Django 3.2.15 on 2022-09-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0027_auto_20220915_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='property_title_no',
            new_name='title_no',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='property_title_no',
            new_name='title_no',
        ),
    ]
