# Generated by Django 3.2.15 on 2022-08-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rent_pw', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('main_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('bath_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('kitchen_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('bedroom_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('living_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('carports', models.IntegerField()),
                ('land_area', models.IntegerField(blank=True, null=True)),
                ('building_area', models.IntegerField(blank=True, null=True)),
                ('air_conditioning', models.IntegerField()),
                ('unit_no', models.IntegerField(blank=True, null=True)),
                ('house_no', models.IntegerField(blank=True, null=True)),
                ('suburb', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('build_date', models.DateField(blank=True, null=True)),
                ('list_date', models.DateField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_properties.category')),
            ],
        ),
    ]
