# Generated by Django 3.2.15 on 2022-09-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_no', models.CharField(default='LT0000', max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('ribbon_feature', models.CharField(default='New Listing', max_length=20)),
                ('description', models.TextField()),
                ('sale_price', models.IntegerField(default=1000000)),
                ('rent_pw', models.IntegerField(default=100000)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('main_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('bath_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('kitchen_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('bedroom_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('living_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('carports', models.IntegerField()),
                ('land_area', models.IntegerField(blank=True, null=True)),
                ('building_area', models.IntegerField(blank=True, null=True)),
                ('air_conditioning', models.IntegerField()),
                ('unit_no', models.IntegerField(blank=True, null=True)),
                ('house_no', models.IntegerField(default='No.', null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(default='Street', max_length=40, null=True)),
                ('suburb', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('build_date', models.DateField(blank=True, null=True)),
                ('list_date', models.DateField(auto_now_add=True)),
                ('list_duration', models.IntegerField(default=30)),
                ('date_available', models.DateField(blank=True, null=True)),
                ('owner_fname', models.CharField(max_length=254, null=True)),
                ('owner_lname', models.CharField(max_length=254, null=True)),
                ('viewings', models.BooleanField(default=True)),
                ('realtor', models.CharField(blank=True, default='Local ReaBook Agent', max_length=256, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_properties.category')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_properties.sector')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'get_latest_by': 'list_date',
            },
        ),
    ]
