# Generated by Django 3.2.15 on 2022-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='realtor',
            field=models.CharField(blank=True, default='ReaBook.net', max_length=256, null=True),
        ),
    ]
