# Generated by Django 3.2.15 on 2022-09-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0002_alter_property_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title_no',
            field=models.CharField(default='LT0000', max_length=254, unique=True),
        ),
    ]
