# Generated by Django 3.2.15 on 2022-08-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0003_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_properties.sector'),
        ),
    ]
