# Generated by Django 3.2.15 on 2022-09-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0003_alter_property_title_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
