# Generated by Django 3.2.15 on 2022-09-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0004_property_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='viewings',
            field=models.BooleanField(default=False),
        ),
    ]
