# Generated by Django 3.2.15 on 2022-08-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0004_property_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='sku',
            new_name='title_no',
        ),
        migrations.AddField(
            model_name='property',
            name='owner_fname',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_lname',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
