# Generated by Django 3.2.15 on 2022-09-26 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_properties', '0005_alter_property_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='realtor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
