# Generated by Django 3.2.15 on 2022-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0005_auto_20220830_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
