# Generated by Django 3.2.15 on 2022-08-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0006_auto_20220830_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_available',
            field=models.DateField(blank=True, null=True),
        ),
    ]
