# Generated by Django 3.2.15 on 2022-09-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0006_alter_property_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rent_pw',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_price',
            field=models.IntegerField(blank=True),
        ),
    ]
