# Generated by Django 3.2.15 on 2022-08-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0007_property_date_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rent_pw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_price',
            field=models.IntegerField(default=0),
        ),
    ]
