# Generated by Django 3.2.15 on 2022-09-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0007_auto_20220926_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='property',
            name='suburb',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='property',
            name='title_no',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
