# Generated by Django 3.2.15 on 2022-08-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0008_auto_20220831_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='list_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
