# Generated by Django 3.2.15 on 2022-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0008_auto_20220926_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rent_pw',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
