# Generated by Django 3.2.15 on 2022-08-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0009_auto_20220831_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ribbon_feature',
            field=models.CharField(default='New Listing', max_length=20),
        ),
    ]
