# Generated by Django 3.2.15 on 2022-09-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0010_auto_20220926_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title_no',
            field=models.CharField(max_length=254),
        ),
    ]
