# Generated by Django 3.2.15 on 2022-09-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0010_property_ribbon_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
