# Generated by Django 3.2.15 on 2022-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0012_alter_property_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rent_pw',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_price',
            field=models.IntegerField(default=1000000),
        ),
    ]
