# Generated by Django 3.2.15 on 2022-09-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0012_alter_property_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='viewings',
            field=models.BooleanField(default=True),
        ),
    ]
