# Generated by Django 3.2.15 on 2022-09-12 07:25
# flake8: noqa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0013_auto_20220909_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'get_latest_by': 'list_date', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='house_no',
            field=models.IntegerField(default='No.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='list_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(default='Street', max_length=40, null=True),
        ),
    ]
