# Generated by Django 3.2.15 on 2022-09-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0014_auto_20220912_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='viewings',
            field=models.BooleanField(default=True),
        ),
    ]
