# Generated by Django 3.2.15 on 2022-09-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0015_property_viewings'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
