# Generated by Django 3.2.15 on 2022-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0016_property_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='selected',
        ),
        migrations.AddField(
            model_name='property',
            name='realtor',
            field=models.CharField(blank=True, default='Local ReaBook Agent', max_length=256, null=True),
        ),
    ]
