# Generated by Django 3.2.15 on 2022-09-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0016_property_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='selected',
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_properties.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='realtor',
            field=models.CharField(blank=True, default='Local ReaBook Agent', max_length=256, null=True),
        ),
    ]
