# Generated by Django 3.2.15 on 2022-09-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_properties', '0018_remove_property_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prop_id_string',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='pk'),
        ),
    ]
