# Generated by Django 3.2.15 on 2022-09-23 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_properties', '0003_alter_property_title_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('client_username', models.CharField(default='Create Username', max_length=40)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.IntegerField(blank=True, default=123456789, null=True)),
                ('client_city', models.CharField(blank=True, max_length=140, null=True)),
                ('client_state', models.CharField(blank=True, max_length=10, null=True)),
                ('client_zip', models.CharField(default='123 45', max_length=10)),
                ('client_country', models.CharField(blank=True, max_length=140, null=True)),
                ('contact_ok', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('client_username', models.CharField(default='Create Username', max_length=40)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.IntegerField(blank=True, default=123456789, null=True)),
                ('client_city', models.CharField(blank=True, max_length=140, null=True)),
                ('client_state', models.CharField(blank=True, max_length=10, null=True)),
                ('client_zip', models.CharField(default='123 45', max_length=10)),
                ('client_country', models.CharField(blank=True, max_length=140, null=True)),
                ('contact_ok', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bookings.question')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=8)),
                ('booking_name', models.CharField(blank=True, default='15 min Viewing', max_length=254, null=True)),
                ('date_of_viewing', models.DateField(default=datetime.date.today)),
                ('time_of_viewing', models.TimeField(default=django.utils.timezone.now)),
                ('client_message', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewing_active', models.BooleanField(default=True)),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('client_username', models.CharField(default='Create Username', max_length=40)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.IntegerField(blank=True, default=123456789, null=True)),
                ('client_city', models.CharField(blank=True, max_length=140, null=True)),
                ('client_state', models.CharField(blank=True, max_length=10, null=True)),
                ('client_zip', models.CharField(default='123 45', max_length=10)),
                ('client_country', models.CharField(blank=True, max_length=140, null=True)),
                ('contact_ok', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bookings.client')),
                ('property_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_properties.property')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
