# Generated by Django 3.2.15 on 2022-09-27 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_bookings', '0006_auto_20220927_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_username',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
