# Generated by Django 3.2.15 on 2022-09-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookings', '0012_alter_booking_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='LoginForm',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
